class EatsureTest{


public static void main(String args[]){
	double priceoftheFood1 = Eatsure.search("rotti");
	double foodpricewithquantity1 = Eatsure.search("rotti",5);
	System.out.println("the price of the  food  is:"+priceoftheFood1);
	System.out.println("the food  price with quantity:"+foodpricewithquantity1);
	double priceoftheFood2 = Eatsure.search("halka pulka");
	double foodpricewithquantity2= Eatsure.search("halka pulka",5);
	System.out.println("the price of the  food  is:"+priceoftheFood2);
	System.out.println("the food  price with quantity:"+foodpricewithquantity2);
	double priceoftheFood3 = Eatsure.search("dal");
	double foodpricewithquantity3 = Eatsure.search("dal",5);
	System.out.println("the price of the  food  is:"+priceoftheFood3);
	System.out.println("the food  price with quantity:"+foodpricewithquantity3);
	double priceoftheFood4 = Eatsure.search("tanduri");
	double foodpricewithquantity4 = Eatsure.search("tanduri",5);
	System.out.println("the price of the  food  is:"+priceoftheFood4);
	System.out.println("the food  price with quantity:"+foodpricewithquantity4);
	double priceoftheFood5 = Eatsure.search("dal makhani");
	double foodpricewithquantity5 = Eatsure.search("dal makhani",5);
	System.out.println("the price of the  food  is:"+priceoftheFood5);
	System.out.println("the food  price with quantity:"+foodpricewithquantity5);
	double priceoftheFood6 = Eatsure.search("chole bhature");
	double foodpricewithquantity6 = Eatsure.search("chole bhature",5);
	System.out.println("the price of the  food  is:"+priceoftheFood6);
	System.out.println("the food  price with quantity:"+foodpricewithquantity6);
	double priceoftheFood7 = Eatsure.search("butter chicken");
	double foodpricewithquantity7 = Eatsure.search("butter chicken",5);
	System.out.println("the price of the  food  is:"+priceoftheFood7);
	System.out.println("the food  price with quantity:"+foodpricewithquantity7);
	double priceoftheFood8 = Eatsure.search("butter rotti");
	double foodpricewithquantity8 = Eatsure.search("butter rotti",5);
	System.out.println("the price of the  food  is:"+priceoftheFood8);
	System.out.println("the food  price with quantity:"+foodpricewithquantity8);
	double priceoftheFood9 = Eatsure.search("maagi rotti");
	double foodpricewithquantity9 = Eatsure.search("maagi rotti",5);
	System.out.println("the price of the  food  is:"+priceoftheFood9);
	System.out.println("the food  price with quantity:"+foodpricewithquantity9);
	double priceoftheFood10 = Eatsure.search("chana masala");
	double foodpricewithquantity10 = Eatsure.search("chana masala",5);
	System.out.println("the price of the  food  is:"+priceoftheFood10);
	System.out.println("the food  price with quantity:"+foodpricewithquantity10);
	double priceoftheFood11 = Eatsure.search("palak panner");
	double foodpricewithquantity11 = Eatsure.search("palak panner",5);
	System.out.println("the price of the  food  is:"+priceoftheFood11);
	System.out.println("the food  price with quantity:"+foodpricewithquantity11);
	double priceoftheFood12 = Eatsure.search("korma");
	double foodpricewithquantity12 = Eatsure.search("korma",5);
	System.out.println("the price of the  food  is:"+priceoftheFood12);
	System.out.println("the food  price with quantity:"+foodpricewithquantity12);
	double priceoftheFood13 = Eatsure.search("rajma");
	double foodpricewithquantity13 = Eatsure.search("rajma",5);
	System.out.println("the price of the  food  is:"+priceoftheFood13);
	System.out.println("the food  price with quantity:"+foodpricewithquantity13);
	double priceoftheFood14 = Eatsure.search("veg corn soup");
	double foodpricewithquantity14 = Eatsure.search("veg corn soup",5);
	System.out.println("the price of the  food  is:"+priceoftheFood14);
	System.out.println("the food  price with quantity:"+foodpricewithquantity14);
	double priceoftheFood15 = Eatsure.search("tava sweet");
	double foodpricewithquantity15 = Eatsure.search("tava sweet",5);
	System.out.println("the price of the  food  is:"+priceoftheFood15);
	System.out.println("the food  price with quantity:"+foodpricewithquantity15);
	double priceoftheFood16 = Eatsure.search("coconut chutney");
	double foodpricewithquantity16 = Eatsure.search("coconut chutney",5);
	System.out.println("the  price of the food is :"+priceoftheFood16);
	System.out.println("the food  price with quantity:"+foodpricewithquantity16);
	double priceoftheFood17=Eatsure.search("chala mirchi");
	double foodpricewithquantity17 = Eatsure.search("chala mirchi",5);
	System.out.println("the  price of the food is :"+priceoftheFood17);
	System.out.println("the food  price with quantity:"+foodpricewithquantity17);
	double priceoftheFood18=Eatsure.search("carrot alva");
	double foodpricewithquantity18 = Eatsure.search("carrot alva",5);
	System.out.println("the  price of the food is :"+priceoftheFood18);
	System.out.println("the food  price with quantity:"+foodpricewithquantity18);
	double priceoftheFood19=Eatsure.search("uppitu");
	double foodpricewithquantity19 = Eatsure.search("uppitu",5);
	System.out.println("the  price of the food is :"+priceoftheFood19);
	System.out.println("the food  price with quantity:"+foodpricewithquantity19);
	double priceoftheFood20=Eatsure.search("batora");
	double foodpricewithquantity20 = Eatsure.search("batora",5);
	System.out.println("the  price of the food is :"+priceoftheFood20);
	System.out.println("the food  price with quantity:"+foodpricewithquantity20);
}
}